const $=id=>document.getElementById(id);
const file=$("file"),video=$("video"),start=$("start"),stopBtn=$("stop"),full=$("full"),small=$("small");
const fctx=full.getContext("2d",{willReadFrequently:true}),sctx=small.getContext("2d",{willReadFrequently:true});
let url=null,stopped=false,shots=[];
[["interval",2],["stable",1],["change",0],["dup",0]].forEach(([id,d])=>$(id).addEventListener("input",()=>$(id+"Out").textContent=Number($(id).value).toFixed(d)));
function fmt(sec){const m=Math.floor(sec/60),s=Math.floor(sec%60).toString().padStart(2,"0");return m+":"+s}
function waitMeta(){return new Promise((resolve,reject)=>{if(video.readyState>=1&&video.videoWidth)return resolve();const ok=()=>{clean();resolve()},bad=()=>{clean();reject(new Error("動画を読み込めません"))},clean=()=>{video.removeEventListener("loadedmetadata",ok);video.removeEventListener("loadeddata",ok);video.removeEventListener("error",bad)};video.addEventListener("loadedmetadata",ok);video.addEventListener("loadeddata",ok);video.addEventListener("error",bad);setTimeout(()=>video.load(),50)})}
file.addEventListener("change",async()=>{start.disabled=true;const f=file.files&&file.files[0];if(!f)return;$("status").textContent="動画を読み込み中…";$("detail").textContent=f.name;if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(f);video.hidden=false;video.src=url;video.load();try{await waitMeta();full.width=video.videoWidth;full.height=video.videoHeight;small.width=64;small.height=Math.max(64,Math.round(64*video.videoHeight/video.videoWidth));start.disabled=false;$("status").textContent="準備完了";$("detail").textContent=fmt(video.duration)+" / "+video.videoWidth+"×"+video.videoHeight}catch(e){$("status").textContent="動画の読み込みに失敗しました";$("detail").textContent="別の画面収録で試してください。"}});
function seek(t){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{clean();reject(new Error("seek timeout"))},5000),done=()=>{clean();resolve()},clean=()=>{clearTimeout(timer);video.removeEventListener("seeked",done)};video.addEventListener("seeked",done,{once:true});video.currentTime=Math.min(Math.max(0,t),Math.max(0,video.duration-.03))})}
function sig(){sctx.drawImage(video,0,0,small.width,small.height);const d=sctx.getImageData(0,0,small.width,small.height).data,a=new Uint8Array(small.width*small.height);for(let i=0,j=0;i<d.length;i+=4,j++)a[j]=Math.round(d[i]*.299+d[i+1]*.587+d[i+2]*.114);return a}
function diff(a,b){if(!a||!b)return 100;let n=0;for(let i=0;i<a.length;i++)n+=Math.abs(a[i]-b[i]);return n/a.length/255*100}
async function capture(t,s){await seek(t);fctx.drawImage(video,0,0,full.width,full.height);const blob=await new Promise(r=>full.toBlob(r,"image/jpeg",.92));const u=URL.createObjectURL(blob),i=shots.length;shots.push({t,s,u,blob});const card=document.createElement("div");card.className="shot";const img=document.createElement("img");img.src=u;const pick=document.createElement("label");pick.className="pick";const check=document.createElement("input");check.type="checkbox";check.className="shotPick";check.dataset.index=i;check.checked=true;const pickText=document.createElement("span");pickText.textContent="PDFに含める";pick.append(check,pickText);const meta=document.createElement("div");meta.textContent="#"+(i+1)+"　"+fmt(t);const a=document.createElement("a");a.href=u;a.download="screen_"+String(i+1).padStart(3,"0")+".jpg";a.textContent="画像を保存";card.append(img,pick,meta,a);$("results").append(card);$("count").textContent=shots.length+"枚";updatePdfButtons()}
stopBtn.onclick=()=>stopped=true;
start.onclick=async()=>{stopped=false;start.disabled=true;stopBtn.disabled=false;$("results").innerHTML="";shots.forEach(x=>URL.revokeObjectURL(x.u));shots=[];$("count").textContent="0枚";updatePdfButtons();const step=+$("interval").value,stableTh=+$("stable").value,changeTh=+$("change").value,dupTh=+$("dup").value;let prev=null,last=null,changed=true,stableN=0;const total=Math.ceil(video.duration/step);$("status").textContent="解析中…";try{for(let n=0,t=0;t<video.duration&&!stopped;n++,t=n*step){await seek(t);const s=sig(),d=diff(prev,s);if(prev){if(d>=changeTh){changed=true;stableN=0}else if(d<=stableTh)stableN++;else stableN=0}if(changed&&stableN>=2){if(!last||diff(last,s)>=dupTh){await capture(t,s);last=s}changed=false;stableN=0}prev=s;const p=Math.min(100,Math.round((n+1)/total*100));$("progress").value=p;$("detail").textContent=p+"%　"+fmt(t)+" / "+fmt(video.duration)+"　検出 "+shots.length+"枚";await new Promise(r=>setTimeout(r,0))}$("status").textContent=stopped?"中止しました":"完了 ✓　"+shots.length+"枚を抽出";if(!stopped)$("progress").value=100}catch(e){$("status").textContent="解析中にエラーが発生しました";$("detail").textContent=e.message}finally{stopBtn.disabled=true;start.disabled=false}};

function updatePdfButtons(){const has=shots.length>0;$("selectAll").disabled=!has;$("clearAll").disabled=!has;$("makePdf").disabled=!has}
$("selectAll").onclick=()=>document.querySelectorAll(".shotPick").forEach(x=>x.checked=true);
$("clearAll").onclick=()=>document.querySelectorAll(".shotPick").forEach(x=>x.checked=false);
function blobToDataURL(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(blob)})}
$("makePdf").onclick=async()=>{const selected=[...document.querySelectorAll(".shotPick:checked")].map(x=>shots[+x.dataset.index]);if(!selected.length){$("status").textContent="PDFにする画像を選択してください";return}const old=$("makePdf").textContent;$("makePdf").disabled=true;$("makePdf").textContent="PDF作成中…";try{const {jsPDF}=window.jspdf;let pdf=null;for(let i=0;i<selected.length;i++){const sh=selected[i],data=await blobToDataURL(sh.blob);const img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=data});const portrait=img.height>=img.width;const orientation=portrait?"p":"l";const w=portrait?210:297,h=portrait?297:210;if(!pdf)pdf=new jsPDF({orientation,unit:"mm",format:"a4",compress:true});else pdf.addPage("a4",orientation);const scale=Math.min(w/img.width,h/img.height),iw=img.width*scale,ih=img.height*scale;pdf.addImage(data,"JPEG",(w-iw)/2,(h-ih)/2,iw,ih,undefined,"FAST");$("detail").textContent="PDF作成中 "+(i+1)+" / "+selected.length}pdf.save("screen-recording-"+new Date().toISOString().slice(0,10)+".pdf");$("status").textContent="PDF作成完了 ✓";$("detail").textContent=selected.length+"枚を順番にPDFへまとめました"}catch(e){$("status").textContent="PDF作成に失敗しました";$("detail").textContent=e.message}finally{$("makePdf").disabled=false;$("makePdf").textContent=old}};
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(()=>{}));